//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoaPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entidad
    {
        public Entidad()
        {
            this.UnidadAdministrativa = new HashSet<UnidadAdministrativa>();
        }
    
        public int IdEntidad { get; set; }
        public string Nombre { get; set; }
        public string Siglas { get; set; }
    
        public virtual ICollection<UnidadAdministrativa> UnidadAdministrativa { get; set; }
    }
}
