//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoaPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicadorMensual
    {
        public int IdIndicadorMensual { get; set; }
        public int IdIndicadorTrimestral { get; set; }
        public string Mes { get; set; }
        public int PrgMetaMen { get; set; }
        public Nullable<int> EjecMetaMen { get; set; }
    
        public virtual IndicadorTrimestral IndicadorTrimestral { get; set; }
    }
}
