//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoaPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicadorAnual
    {
        public IndicadorAnual()
        {
            this.IndicadorTrimestral = new HashSet<IndicadorTrimestral>();
        }
    
        public int IdIndicador { get; set; }
        public int IdProducto { get; set; }
        public int IdPOAResultado { get; set; }
        public int IdUnidadOperativa { get; set; }
        public int Anio { get; set; }
        public string Indice { get; set; }
        public string DescripcionIndicador { get; set; }
        public string DescripcionMeta { get; set; }
        public decimal ValorMeta { get; set; }
        public Nullable<bool> CriterioGenVI { get; set; }
        public Nullable<bool> CriterioGenMNG { get; set; }
        public Nullable<bool> CriterioGenDS { get; set; }
        public string Limitantes { get; set; }
        public string Acciones { get; set; }
    
        public virtual POADetalle POADetalle { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual UnidadOperativa UnidadOperativa { get; set; }
        public virtual ICollection<IndicadorTrimestral> IndicadorTrimestral { get; set; }
    }
}
