//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoaPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicadorTrimestral
    {
        public IndicadorTrimestral()
        {
            this.IndicadorMensual = new HashSet<IndicadorMensual>();
        }
    
        public int IdIndicadorTrimestral { get; set; }
        public int IdIndicador { get; set; }
        public int Trimestre { get; set; }
        public int PrgMetaTrim { get; set; }
        public Nullable<int> EjecMetaTrim { get; set; }
    
        public virtual IndicadorAnual IndicadorAnual { get; set; }
        public virtual ICollection<IndicadorMensual> IndicadorMensual { get; set; }
    }
}
