//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoaPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POA
    {
        public POA()
        {
            this.POADetalle1 = new HashSet<POADetalle>();
        }
    
        public int IdPOA { get; set; }
        public int IdEntidad { get; set; }
        public int IdUnidadAdministrativa { get; set; }
        public int Anio { get; set; }
        public int IdObjetivoEstrategico { get; set; }
        public int IdActividadEstrategica { get; set; }
        public string Observaciones { get; set; }
    
        public virtual ActividadEstrategica ActividadEstrategica { get; set; }
        public virtual ObjetivoEstrategico ObjetivoEstrategico { get; set; }
        public virtual POADetalle POADetalle { get; set; }
        public virtual ICollection<POADetalle> POADetalle1 { get; set; }
    }
}
