//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoaPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado
    {
        public Resultado()
        {
            this.POADetalle = new HashSet<POADetalle>();
        }
    
        public int IdResultado { get; set; }
        public string Indice { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<POADetalle> POADetalle { get; set; }
    }
}
